in case the input format is not as expected, and no 'doc' property can be found, return nil instead of failing while accessing nil array index
this will avoid having the following error : Error: undefined method `[]' for nil:NilClass  Exception: NoMethodError